Vagrant.configure("2") do |config|

  config.vm.box = "debian/buster64"


  config.vm.define "git_server" do |git_server|
    git_server.vm.provider "virtualbox" do |vb|
       vb.memory = "512"
    end

    git_server.vm.network "private_network", ip: "192.168.33.13"
    git_server.vm.hostname = 'git-server'

    git_server.vm.provision "shell", inline: <<-SHELL
      echo "Adding SSH Key"
      echo 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC84q7fw+wfx1lPh5dch0R7sVwksfJABDBeQImOurPrsHp4tcWCzRbZB67xhnysGEpsbIZ6EFmM7DdDxAxuo92VCwvysznFgGQZhxsjnyL5y6w55kIywPM4m9GAmMxWSP2MkjQKcrMfEzNgs6z1bIzcJmfz+r3WR4Oqd8vbQd3sMZzdNlNrIN5Btf1D5WxCx7eRxWHvOvOFKYeJyZ7L/09Z8E4LH+2DCAb3lC0VB40JPI1FwpmhfYHaxKF2JlpCjvi3qrS0VntWhw1tdhH/J9tdBu5BhsQEbYsu/Ych8DhZhhVc00N2oJuhxU+90yl/HHhL5Jgo054KHSIchCZM6/03 root@debian
' >> /home/vagrant/.ssh/authorized_keys
    SHELL
  end

end
